### ISSUE TITLE
EPEERINVALID error while installing

### ISSUE THREAD

**Issue by undavide** [codearoni/generator-gizmo#2]
Hi,
I've got this error while installing generator-gizmo:

`EPEERINVALID generator-gizmo@0.0.3 requires a peer of yo@>=1.0.0 but none was installed.`

But `yo --version` returns `1.5.0`. Please let me know, thanks!

-Davide

**Comment by codearoni** [comment]
heya Davide!
Could you provide me with your npm version as well? 2.x and 3.x handle peer dependencies differently.

**Comment by undavide** [comment]
Sure, npm is 3.3.6, thanks for the support!

**Comment by codearoni** [comment]
Sorry the delay. This does appear to be an issue with how peer dependencies are handled with npm 3.x vs 2.x.

I will notify again when a fix is up.

**Comment by codearoni** [comment]
@undavide I've pushed a fix and tested it with npm 3.3.6 and 3.5.1. Let me know how it goes for you. I'll close this if it's good to go. Cheers

**Comment by undavide** [comment]
Hi,
I'm afraid the output is:

```
sudo npm install -g generator-gizmo
Password:

> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/generator-gizmo/node_modules/spawn-sync
> node postinstall

/usr/local/lib
├─┬ generator-gizmo@0.0.5 
│ └─┬ yeoman-generator@0.21.1
│   ├─┬ cross-spawn@2.1.0
│   │ └── cross-spawn-async@2.1.1 
│   └─┬ download@4.4.3
│     └── caw@1.2.0 
└── UNMET PEER DEPENDENCY yo@^1.0.0

npm WARN EPEERINVALID generator-gizmo@0.0.5 requires a peer of yo@^1.0.0 but none was installed.
```

I've tried removing and reinstalling yo (I assume npm correctly fetches latest generator-gizmo, since now it's 0.0.5) but the output is similar:

```
install -g generator-gizmo

> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/generator-gizmo/node_modules/spawn-sync
> node postinstall

/usr/local/lib
├── generator-gizmo@0.0.5 
└── UNMET PEER DEPENDENCY yo@^1.0.0

npm WARN EPEERINVALID generator-gizmo@0.0.5 requires a peer of yo@^1.0.0 but none was installed.
```

Thanks for the support,
-Davide

**Comment by codearoni** [comment]
np Davide. Give 0.0.6. a whirl and let me know.

I've been able to reproduce this warning and it's a bit perplexing. My fix opens up the possibility of a user running Gizmo with a pre-1.0 version of yo (circa 2012) without a warning. I'm pretty confident that is a non-existent use-case :smile: but I'll cross that bridge if it appears on the horizon.

**Comment by undavide** [comment]
Arrgh. Slightly different error this time:

`EPEERINVALID generator-gizmo@0.0.6 requires a peer of yo@* but none was installed.`

I'm afraid I still can't install it :-( npm can be a nightmare...!
Thanks,

Davide

**Comment by codearoni** [comment]
@undavide 

Very strange. I cannot recreate this and get an EPEERINVALID error. 

My node console has a warning:
npm WARN peerDependencies The peer dependency yo@\* included from generator-gizmo will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

But the installation executes just fine. Node v4.2.2, NPM v2.14.7

Could you run a "npm list --depth=0 -g" command and paste the output?

**Comment by codearoni** [comment]
@undavide 
Disregard my previous request. I've been researching this issue and it's popped up in several popular yeoman generators. A surprising amount of them have dropped peerDeps from their package. I'm taking the highroad and adding a prefer global flag, like several other generators have done.

I love the idea of peerDeps but the dissonance in functionality between npm versions appears to be more trouble than it's worth. Give 0.0.7 a go whenever you get a chance. Happy holidays!

**Comment by undavide** [comment]
By Jove, I got it!
Thanks for your support, I've been able to install it finally - phew :-)
